#!/bin/bash
#SBATCH --job-name=hedge_r5
#SBATCH --output=hedge_r5_%j.out
#SBATCH --error=hedge_r5_%j.err
#SBATCH --partition=general
#SBATCH --time=48:00:00
#SBATCH --mem=128G
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --mail-type=BEGIN,END,FAIL

module load dealii/9.7.1_umfpack
source /share/apps/common/SPACK_v110_release_a2/spack/opt/spack/linux-x86_64/dealii-9.7.1-kr766e7zm3gq6q7t67vefndkrhcyvmrw/.spack/spack-build-env.txt

cd /share/ceph/scratch/mg6f4/dealii_runs/hedge_r5

/home/mg6f4/PhD-Project/PhaseField/build-release/ferrofluid \
  --hedgehog \
  --refinement 5 \
  --no_amr \
  --no_adaptive_dt \
  --direct \
  --verbose